@echo off

set PROJ_DIR=%~dp0..

cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=gcc -DCMAKE_CXX_COMPILER:FILEPATH=g++ --no-warn-unused-cli -S%PROJ_DIR% -B%PROJ_DIR%\build -G "MinGW Makefiles"

exit /b